### ISSUE TITLE
register doesn't work

### ISSUE THREAD

**Issue by ay0o5h** [keikaavousi/fake-store-api#90]
when i create new user it tell me create succussfuly but when i try to login it tell me username or password incorrect

**Comment by splincool** [comment]
In my opinion, it happens because your new user is not added to database. You only get a successful message during creation. This warning shows under the "Add a new user" code example:

_"If you send an object like the code above, it will return you an object with a new id. remember that nothing in real will insert into the database. so if you want to access the new id you will get a 404 error."_
